name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
version: 8.0.2
publish_to: none
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin
      web:
        default_package: image_cropper_for_web

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface: 
    git: https://github.com/kumsumit/image_cropper_platform_interface.git
  image_cropper_for_web:
    git: https://github.com/kumsumit/image_cropper_for_web.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
